### ISSUE TITLE
JEE 6 support possible

### ISSUE THREAD

**Issue by nskmda** [soulwing/pinject#1]
First of all, thanks for a great job!
Is it possible to have support for JEE 6?

I tried **pinject** on WildFly 8.2.0 and it worked perfectly fine.
But then our requirements changed and now I need the same in JBoss 6.3.x.
The app doesn't seem to deploy properly and I see WELD 2.x.x dependency in the POM.

**Comment by ceharris** [comment]
The Weld dependency is only used during testing of the extension.

Portable CDI extensions were added in Java EE 7.  Since Pinject is a portable CDI injection, it just isn't possible to make it work in Java EE 6.  It might be possible do something JBoss 6.3.x specific, but that would be a significant project.

Sorry.   :-(

**Comment by nskmda** [comment]
it's okay.
thanks, anyway
